;;; tests-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from test-chime-all-day-events.el

(register-definition-prefixes "test-chime-all-day-events" '("test-allday--create-event"))


;;; Generated autoloads from test-chime-apply-blacklist.el

(register-definition-prefixes "test-chime-apply-blacklist" '("test-chime-apply-blacklist-"))


;;; Generated autoloads from test-chime-apply-whitelist.el

(register-definition-prefixes "test-chime-apply-whitelist" '("test-chime-apply-whitelist-"))


;;; Generated autoloads from test-chime-check-event.el

(register-definition-prefixes "test-chime-check-event" '("test-chime-check-event-"))


;;; Generated autoloads from test-chime-check-interval.el

(register-definition-prefixes "test-chime-check-interval" '("test-chime-check-interval-"))


;;; Generated autoloads from test-chime-extract-time.el

(register-definition-prefixes "test-chime-extract-time" '("test-chime-extract-time-"))


;;; Generated autoloads from test-chime-format-event-for-tooltip.el

(register-definition-prefixes "test-chime-format-event-for-tooltip" '("test-chime-format-event-for-tooltip-"))


;;; Generated autoloads from test-chime-gather-info.el

(register-definition-prefixes "test-chime-gather-info" '("test-chime-gather-info-"))


;;; Generated autoloads from test-chime-group-events-by-day.el

(register-definition-prefixes "test-chime-group-events-by-day" '("test-chime-"))


;;; Generated autoloads from test-chime-has-timestamp.el

(register-definition-prefixes "test-chime-has-timestamp" '("test-chime-has-timestamp-"))


;;; Generated autoloads from test-chime-modeline.el

(register-definition-prefixes "test-chime-modeline" '("test-chime-modeline-"))


;;; Generated autoloads from test-chime-notification-text.el

(register-definition-prefixes "test-chime-notification-text" '("test-chime-notification-text-"))


;;; Generated autoloads from test-chime-notifications.el

(register-definition-prefixes "test-chime-notifications" '("test-chime-notifications-"))


;;; Generated autoloads from test-chime-notify.el

(register-definition-prefixes "test-chime-notify" '("test-chime-notify-"))


;;; Generated autoloads from test-chime-overdue-todos.el

(register-definition-prefixes "test-chime-overdue-todos" '("test-"))


;;; Generated autoloads from test-chime-process-notifications.el

(register-definition-prefixes "test-chime-process-notifications" '("test-chime-process-notifications-"))


;;; Generated autoloads from test-chime-sanitize-title.el

(register-definition-prefixes "test-chime-sanitize-title" '("test-chime-sanitize-title-"))


;;; Generated autoloads from test-chime-time-left.el

(register-definition-prefixes "test-chime-time-left" '("test-chime-time-left-"))


;;; Generated autoloads from test-chime-timestamp-parse.el

(register-definition-prefixes "test-chime-timestamp-parse" '("test-chime-timestamp-parse-"))


;;; Generated autoloads from test-chime-timestamp-within-interval-p.el

(register-definition-prefixes "test-chime-timestamp-within-interval-p" '("test-chime-timestamp-within-interval-p-"))


;;; Generated autoloads from test-chime-tooltip-bugs.el

(register-definition-prefixes "test-chime-tooltip-bugs" '("test-tooltip-bugs-"))


;;; Generated autoloads from test-chime-update-modeline.el

(register-definition-prefixes "test-chime-update-modeline" '("test-chime-update-modeline-"))


;;; Generated autoloads from test-chime-whitelist-blacklist-conflicts.el

(register-definition-prefixes "test-chime-whitelist-blacklist-conflicts" '("test-chime-conflicts-"))


;;; Generated autoloads from testutil-general.el

(register-definition-prefixes "testutil-general" '("chime-"))


;;; Generated autoloads from testutil-time.el

(register-definition-prefixes "testutil-time" '("test-time" "with-test-time"))

;;; End of scraped data

(provide 'tests-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; tests-autoloads.el ends here
